---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iyastreb/spring
          searchPaths: config-repo

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh,info,health
