---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: subject
words: I,You,He,She,It,Ilia

---
spring:
  profiles: verb
words: love,hate,join,struggle,fight,take,waste

---
spring:
  profiles: article
words: a,the,one

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,lazy,big,little

---
spring:
  profiles: noun
words: world,stack,seat,oak,list,map,set,hash

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball

---
spring:
  profiles: sentence
words: 
server:
  port: 8020
